### ISSUE TITLE
Net::Etcd use cases

### ISSUE THREAD

**Issue by hexfusion** [hexfusion/perl-net-etcd#58]
Perl is often times left out of the conversation when we talk about cloud development and distributed systems. As users and contributors of the module, I would like to hear about your use cases. Please take a minute to share if possible. Maybe down the road we can come up with a general doc outlining some examples.

/cc @michaelfung @foobargeez

**Comment by michaelfung** [comment]
Well, I want to automate the initialization of etcd. Like creating users, roles, and populate key/values. My script reads these from a YAML file like:

```
roles:
    -   name: guest
        perms:
            -   key: pub/
                prefix: 1
                rights: read

            -   key: test
                prefix: 0
                rights: readwrite

    -   name: shadow_services
        perms:
            -   key: siot/shadow/
                prefix: 1
                rights: readwrite

            -   key: siot/mqtt
                prefix: 0
                rights: read

users:
    -   name: test
        password: test1234
        roles:
            - guest

    -   name: shadow_services
        password: shadow1234
        roles:
            - guest
            - shadow_services

keys:
    -   path: siot/mqtt
        value:
            host: 127.0.0.1
            keep_alive_timer: 60
            port: 1887
            user_secrets_ttl: 300

    -   path: siot/shadow/get
        value:
            log_file: /tmp/shadow-service.log
            log_level: debug
            socket_path: ipc:///tmp/shadow-get.sock
            stat_interval: 300
            listen_addr: 127.0.0.1
            listen_port: 8804

    -   path: siot/redis
        value:
            host: localhost
            password: VO4d4a7ngmBg7x-_dIpE1g
            port: 6379
```
